[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[[example]]
name = "basic"
path = "../../examples/basic/main.rs"

[[example]]
name = "sprite"
path = "../../examples/sprite/main.rs"

[[example]]
name = "input"
path = "../../examples/input/main.rs"

[[example]]
name = "full"
path = "../../examples/full/main.rs"

[dependencies]
platform = { path = "../platform" }
graphics = { path = "../graphics" }
glam = "0.29"
thiserror = "2"
